♻️ Strict Typescript
manuel-rw/jellyfin-discord-music-bot pull request #149
Opened 2023-03-29 20:13 UTC by manuel-rw

2023-03-31 21:27 UTC, manuel-rw commented
FYI: The SonarCloud can be ignored. I am migrating to https://deepsource.io/ anyway.

2023-04-01 20:33 UTC, Meierschlumpf requested changes

2023-04-01 20:33 UTC, Meierschlumpf commented on src/clients/discord/discord.config.service.ts
> +      token: process.env.DISCORD_CLIENT_TOKEN ?? '',
would it be possible to just throw an exception that tells the dev that he should define the client token

2023-04-01 20:33 UTC, Meierschlumpf commented on src/clients/discord/discord.voice.service.ts
> +      this.logger.error(`AudioResource or volume was undefined`);
Do you not want to tell the user, that something went wrong?

2023-04-01 20:33 UTC, Meierschlumpf commented on src/clients/jellyfin/jellyfin.service.ts
> +      process.env.JELLYFIN_SERVER_ADDRESS ?? '',
throw an error as well

2023-04-01 20:33 UTC, Meierschlumpf commented on src/clients/jellyfin/jellyfin.service.ts
> +          response.data.SessionInfo.UserId === undefined
change to `response.data.SessionInfo?.UserId === undefined`

2023-04-01 20:33 UTC, Meierschlumpf commented on src/commands/play/play.comands.ts
> +            return embedBuilder.setThumbnail(remoteImage.Url ?? '');
Maybe use a default image

2023-04-01 20:33 UTC, Meierschlumpf commented on src/commands/play/play.comands.ts
> +      .find(() => true);
this looks stupid 😂

2023-04-02 15:41 UTC, merged